
[project]
name = "awscdk-python-template"
version = "0.1.0"
description = "Somewhat opinionated project template for AWS CDK-based projects in Python"
authors = [
    {name = "Erik Lundevall Zara", email = "45368867+eriklz@users.noreply.github.com"},
]
dependencies = [
    "aws-cdk-lib>=2.81.0",
    "icecream>=2.1.3",
    "constructs>=10.2.32",
    "typing-extensions>=4.6.2",
    "tomli>=2.0.1",
    "structlog>=23.1.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.270",
    "black>=23.3.0",
    "pytest>=7.3.1",
    "pre-commit>=3.3.2",
]
